---@type LazySpec
return {
  "suiramdev/cursorcli.nvim",
  name = "cursorcli.nvim",
  dev = true,
  lazy = true,
  cmd = {
    "CursorCliOpen",
    "CursorCliOpenWithLayout",
    "CursorCliClose",
    "CursorCliToggle",
    "CursorCliRestart",
    "CursorCliResume",
    "CursorCliListSessions",
    "CursorCliNew",
    "CursorCliSelect",
    "CursorCliRename",
    "CursorCliAddSelection",
    "CursorCliFixErrorAtCursor",
    "CursorCliFixErrorAtCursorInNewSession",
    "CursorCliAddVisualSelectionToNewSession",
    "CursorCliQuickEdit",
  },
  keys = {
    {
      "<Leader>af",
      "<Cmd>CursorCliOpenWithLayout float<CR>",
      desc = "Open Cursor CLI (floating window)",
      mode = "n",
    },
    {
      "<Leader>av",
      "<Cmd>CursorCliOpenWithLayout vsplit<CR>",
      desc = "Open Cursor CLI (vertical split)",
      mode = "n",
    },
    {
      "<Leader>ah",
      "<Cmd>CursorCliOpenWithLayout hsplit<CR>",
      desc = "Open Cursor CLI (horizontal split)",
      mode = "n",
    },
    {
      "<Leader>ac",
      function() require("cursorcli").close() end,
      desc = "Close Cursor CLI terminal",
      mode = "n",
    },
    {
      "<Leader>an",
      function() require("cursorcli").new_chat() end,
      desc = "New Cursor CLI chat",
      mode = "n",
    },
    {
      "<Leader>as",
      function() require("cursorcli").select_chat() end,
      desc = "Select chat (fuzzy finder with preview)",
      mode = "n",
    },
    {
      "<Leader>ar",
      function() require("cursorcli").rename_chat() end,
      desc = "Rename current Cursor CLI chat",
      mode = "n",
    },
    {
      "<Leader>aR",
      function() require("cursorcli").resume() end,
      desc = "Resume last Cursor CLI chat",
      mode = "n",
    },
    {
      "<Leader>ax",
      function() require("cursorcli").restart() end,
      desc = "Restart Cursor CLI (new session in current chat)",
      mode = "n",
    },
    {
      "<Leader>al",
      function() require("cursorcli").list_sessions() end,
      desc = "List Cursor CLI sessions (agent ls)",
      mode = "n",
    },
    {
      "<Leader>aa",
      function() require("cursorcli").add_visual_selection() end,
      desc = "Add selection to chat",
      mode = "x",
    },
    {
      "<Leader>aq",
      "<Esc><Cmd>CursorCliQuickEdit<CR>",
      desc = "Quick Edit selection",
      mode = "x",
    },
    {
      "<Leader>aA",
      function() require("cursorcli").request_fix_error_at_cursor_in_new_session() end,
      desc = "Fix error at cursor (new session)",
      mode = "n",
    },
    {
      "<Leader>aA",
      function() require("cursorcli").add_visual_selection_to_new_session() end,
      desc = "Add selection to new session",
      mode = "x",
    },
  },
  config = function()
    require("cursorcli").setup {
      command = { "agent" },
    }
  end,
}
